/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaEntidad.clsEClase;
import CapaNegocio.clsItem;
import CapaNegocio.clsNClase;
import CapaNegocio.clsNCurso;
import CapaNegocio.clsNDocente;
import CapaNegocio.clsNEmpleado;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;

/**
 *
 * @author david
 */
public class frmClase extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmClase.class.getName());

    /**
     * Creates new form frmCargo
     */
    
    //DEFINIR UNA NUEVA TABLA
    public static DefaultTableModel modelo = new DefaultTableModel();
    public static int fila = 0;
    
    public frmClase() {
        initComponents();
        
        //DEFINIR LAS COLUMNAS DE LA TABLA
        modelo.addColumn("CODIGO");
        modelo.addColumn("DESCRIPCION");
        
        tblClase.setModel(modelo);
        
        mtdCargarCombos();
    }
    
    private void mtdCargarCombos() {
        try {
            // 1. Cargar Empleados
            clsNEmpleado objNE = new clsNEmpleado();
            ResultSet rsE = objNE.mtdListarEmpleado();
            cmbEmpleado.removeAllItems();
            while (rsE.next()) {
                cmbEmpleado.addItem(new clsItem(rsE.getString("dni"), rsE.getString("nombre")));
            }

            // 2. Cargar Cursos
            clsNCurso objNCu = new clsNCurso();
            ResultSet rsCu = objNCu.mtdListarCurso();
            cmbCurso.removeAllItems();
            while (rsCu.next()) {
                cmbCurso.addItem(new clsItem(rsCu.getString("codigo"), rsCu.getString("nombre")));
            }

            // 3. Cargar Docentes
            clsNDocente objNDo = new clsNDocente();
            ResultSet rsDo = objNDo.mtdListarDocente();
            cmbDocente.removeAllItems();
            while (rsDo.next()) {
                cmbDocente.addItem(new clsItem(rsDo.getString("codigo"), rsDo.getString("nombre")));
            }
        } catch (Exception e) {
            System.out.println("Error cargando combos: " + e.getMessage());
        }
    }
    
    public void mtdListar() {
        
        clsNClase objNCl = new clsNClase();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Clase");
        modelo.addColumn("Empleado");
        modelo.addColumn("Curso");
        modelo.addColumn("Docente");

        tblClase.setModel(modelo);
        ResultSet rs = objNCl.mtdListarClase();
        Object[] fila = new Object[4];

        try {
            while (rs.next()) {
                fila[0] = rs.getString("idclase");
                fila[1] = rs.getString("empleado"); // Viene del JOIN
                fila[2] = rs.getString("curso");    // Viene del JOIN
                fila[3] = rs.getString("docente");  // Viene del JOIN
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void mtdLimpiar() {
        txtIdClase.setText("");
        cmbEmpleado.setSelectedIndex(0);
        cmbCurso.setSelectedIndex(0);
        cmbDocente.setSelectedIndex(0);
        txtIdClase.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCargo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtIdClase = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        lblCurso = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        cmbEmpleado = new javax.swing.JComboBox();
        cmbCurso = new javax.swing.JComboBox();
        cmbDocente = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClase = new javax.swing.JTable();
        lblBCodigo = new javax.swing.JLabel();
        txtBCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("MATENIMIENTO CLASE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(0, 0, 0));
        lblCargo.setText("ID CLASE");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion.setText("EMPLEADO");

        txtIdClase.setBackground(new java.awt.Color(214, 234, 223));
        txtIdClase.setForeground(new java.awt.Color(0, 0, 0));

        btnAgregar.setBackground(new java.awt.Color(204, 255, 255));
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(204, 255, 255));
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(204, 255, 255));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnListar.setBackground(new java.awt.Color(204, 255, 255));
        btnListar.setForeground(new java.awt.Color(0, 0, 0));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(this::btnListarActionPerformed);

        lblCurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(0, 0, 0));
        lblCurso.setText("CURSO");

        lblDocente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocente.setForeground(new java.awt.Color(0, 0, 0));
        lblDocente.setText("DOCENTE");

        cmbEmpleado.setBackground(new java.awt.Color(214, 234, 223));
        cmbEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        cmbEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCurso.setBackground(new java.awt.Color(214, 234, 223));
        cmbCurso.setForeground(new java.awt.Color(0, 0, 0));
        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbDocente.setBackground(new java.awt.Color(214, 234, 223));
        cmbDocente.setForeground(new java.awt.Color(0, 0, 0));
        cmbDocente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDocente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdClase, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(cmbEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDocente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(txtIdClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(cmbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurso)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDocente)
                    .addComponent(cmbDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnListar))
                .addGap(33, 33, 33))
        );

        tblClase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClase);

        lblBCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBCodigo.setText("BUSCAR CODIGO");

        txtBCodigo.setBackground(new java.awt.Color(214, 234, 223));
        txtBCodigo.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscar.setBackground(new java.awt.Color(204, 255, 255));
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblBCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBCodigo)
                    .addComponent(txtBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        clsEClase objECl = new clsEClase();
        clsNClase objNCl = new clsNClase();
        
        objECl.setIdclase(txtIdClase.getText());

        // Capturamos los IDs de los 3 combos usando nuestra clase clsItem
        clsItem emp = (clsItem) cmbEmpleado.getSelectedItem();
        clsItem cur = (clsItem) cmbCurso.getSelectedItem();
        clsItem doc = (clsItem) cmbDocente.getSelectedItem();

        objECl.setDniemp(emp.getId());
        objECl.setCodcurso(cur.getId());
        objECl.setCoddoc(doc.getId());

        if (objNCl.mtdAgregarClase(objECl)) {
            JOptionPane.showMessageDialog(null, "Clase programada con éxito");
            mtdListar();
            mtdLimpiar();
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        clsEClase objECl = new clsEClase();
        clsNClase objNCl = new clsNClase();
        
        if (txtIdClase.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una clase de la tabla");
            return;
        }

        // 1. Asignar el ID de la clase
        objECl.setIdclase(txtIdClase.getText());

        // 2. Capturar los objetos seleccionados de los 3 combos
        clsItem emp = (clsItem) cmbEmpleado.getSelectedItem();
        clsItem cur = (clsItem) cmbCurso.getSelectedItem();
        clsItem doc = (clsItem) cmbDocente.getSelectedItem();

        // 3. Pasar los IDs a la entidad
        objECl.setDniemp(emp.getId());
        objECl.setCodcurso(cur.getId());
        objECl.setCoddoc(doc.getId());

        // 4. Ejecutar la modificación en la Capa Negocio
        if (objNCl.mtdModificarClase(objECl)) {
            JOptionPane.showMessageDialog(null, "Registro actualizado correctamente");
            mtdListar();
            mtdLimpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar");
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        clsEClase objECl = new clsEClase();
        clsNClase objNCl = new clsNClase();
        
        if (txtIdClase.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese o seleccione un ID de Clase");
            return;
        }

        objECl.setIdclase(txtIdClase.getText());

        int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar esta programación de clase?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            if (objNCl.mtdEliminarClase(objECl)) {
                JOptionPane.showMessageDialog(null, "Clase eliminada");
                mtdListar();
                mtdLimpiar();
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        mtdLimpiar();
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        clsEClase objECl = new clsEClase();
        clsNClase objNCl = new clsNClase();
        
        String idBuscar = txtBCodigo.getText(); // O el campo que uses para buscar

        if (idBuscar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID para buscar");
            return;
        }

        objECl.setIdclase(idBuscar);
        ResultSet rs = objNCl.mtdBuscarClase(objECl);

        try {
            if (rs.next()) {
                txtIdClase.setText(rs.getString("idclase"));

                // Los códigos FK que vienen de la base de datos
                String dniVal = rs.getString("dniemp");
                String cursoVal = rs.getString("codcurso");
                String docVal = rs.getString("coddoc");

                // Seleccionar en los combos por ID (no por texto)
                mtdSeleccionarComboPorId(cmbEmpleado, dniVal);
                mtdSeleccionarComboPorId(cmbCurso, cursoVal);
                mtdSeleccionarComboPorId(cmbDocente, docVal);

            } else {
                JOptionPane.showMessageDialog(null, "No se encontró ningún registro con ese ID");
            }
        } catch (SQLException e) {
            System.out.println("Error en búsqueda: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Método auxiliar necesario para el buscador (Selecciona por el ID oculto del clsItem)
    private void mtdSeleccionarComboPorId(JComboBox combo, String id) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            clsItem item = (clsItem) combo.getItemAt(i);
            if (item.getId().equals(id)) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void tblClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClaseMouseClicked

        int fila = tblClase.getSelectedRow();
        if (fila != -1) {
            txtIdClase.setText(tblClase.getValueAt(fila, 0).toString());

            // Función para seleccionar por texto en combos
            mtdSeleccionarCombo(cmbEmpleado, tblClase.getValueAt(fila, 1).toString());
            mtdSeleccionarCombo(cmbCurso, tblClase.getValueAt(fila, 2).toString());
            mtdSeleccionarCombo(cmbDocente, tblClase.getValueAt(fila, 3).toString());
        }

    }//GEN-LAST:event_tblClaseMouseClicked

    private void mtdSeleccionarCombo(JComboBox combo, String valor) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            if (combo.getItemAt(i).toString().equals(valor)) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        mtdListar();
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmClase().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmbCurso;
    private javax.swing.JComboBox cmbDocente;
    private javax.swing.JComboBox cmbEmpleado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBCodigo;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblClase;
    private javax.swing.JTextField txtBCodigo;
    private javax.swing.JTextField txtIdClase;
    // End of variables declaration//GEN-END:variables
}
