/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaEntidad.clsEDetalleMatricula;
import CapaNegocio.clsNDetalleMatricula;
import CapaNegocio.clsItem;
import CapaNegocio.clsNCurso;
import CapaNegocio.clsNMatricula;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author david
 */
public class frmDetalleMatricula extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmDetalleMatricula.class.getName());

    /**
     * Creates new form frmCargo
     */
    
    //DEFINIR UNA NUEVA TABLA
    public static DefaultTableModel modelo = new DefaultTableModel();
    public static int fila = 0;
    
    public frmDetalleMatricula() {
        initComponents();
        
        //DEFINIR LAS COLUMNAS DE LA TABLA
        modelo.addColumn("IDMATRICULA");
        modelo.addColumn("CURSO");
        
        tblDetalleMatricula.setModel(modelo);
        
        mtdCargarComboCurso();
        mtdCargarComboMatricula();
    }
    
    public void mtdListar(int idMatricula) {
        
        clsEDetalleMatricula objEDM = new clsEDetalleMatricula();
        clsNDetalleMatricula objNDM = new clsNDetalleMatricula();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("IDMATRICULA");
        modelo.addColumn("CURSO");

        tblDetalleMatricula.setModel(modelo);
        objEDM.setIdmatricula(idMatricula);

        ResultSet rs = objNDM.mtdListarDetalle(objEDM);
        Object[] fila = new Object[2];

        try {
            while (rs.next()) {
                // Cambia rs.getInt("IDMATRICULA") por el ID que pasaste por parámetro
                fila[0] = idMatricula;
                // Cambia "CURSO" por el nombre de la columna en tu SQL de la capa negocio
                fila[1] = rs.getString("nombre"); // O "codcurso" según prefieras ver
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void mtdLimpiar() {
        cmbMatricula.setSelectedIndex(0);
        cmbCurso.setSelectedIndex(0);
        txtBCodigo.setText("");
    }
    
    private void mtdCargarComboCurso() {
        
        clsNCurso objNCu = new clsNCurso();
        
        try {
            ResultSet rs = objNCu.mtdListarCurso();
            cmbCurso.removeAllItems();
            while (rs.next()) {
                // Usamos la clase clsItem que creamos antes
                cmbCurso.addItem(new clsItem(rs.getString("codigo"), rs.getString("nombre")));
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    private void mtdCargarComboMatricula() {
        try {
            clsNMatricula objNM = new clsNMatricula();
            ResultSet rs = objNM.mtdListarMatricula();
            cmbMatricula.removeAllItems();

            while (rs.next()) {
                // Obtenemos el ID de la base de datos
                String idString = String.valueOf(rs.getInt("idmatricula"));

                // Agregamos al combo: el ID será tanto la llave como el texto visible
                cmbMatricula.addItem(new clsItem(idString, idString));
            }
        } catch (Exception e) {
            System.out.println("Error cargando combo matrícula: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIdMatricula = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        cmbMatricula = new javax.swing.JComboBox();
        cmbCurso = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleMatricula = new javax.swing.JTable();
        lblBCodigo = new javax.swing.JLabel();
        txtBCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("MATENIMIENTO DETALLE MATRICULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        lblIdMatricula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdMatricula.setForeground(new java.awt.Color(0, 0, 0));
        lblIdMatricula.setText("IDMATRICULA");

        lblCurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(0, 0, 0));
        lblCurso.setText("CURSO");

        btnAgregar.setBackground(new java.awt.Color(204, 255, 255));
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(204, 255, 255));
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(204, 255, 255));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnListar.setBackground(new java.awt.Color(204, 255, 255));
        btnListar.setForeground(new java.awt.Color(0, 0, 0));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(this::btnListarActionPerformed);

        cmbMatricula.setBackground(new java.awt.Color(214, 234, 223));
        cmbMatricula.setForeground(new java.awt.Color(0, 0, 0));
        cmbMatricula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCurso.setBackground(new java.awt.Color(214, 234, 223));
        cmbCurso.setForeground(new java.awt.Color(0, 0, 0));
        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdMatricula, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCurso, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbMatricula, 0, 285, Short.MAX_VALUE)
                            .addComponent(cmbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdMatricula)
                    .addComponent(cmbMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnListar))
                .addGap(33, 33, 33))
        );

        tblDetalleMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetalleMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleMatriculaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetalleMatricula);

        lblBCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBCodigo.setText("BUSCAR CODIGO");

        txtBCodigo.setBackground(new java.awt.Color(214, 234, 223));
        txtBCodigo.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscar.setBackground(new java.awt.Color(204, 255, 255));
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblBCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBCodigo)
                    .addComponent(txtBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        clsEDetalleMatricula objEDM = new clsEDetalleMatricula();
        clsNDetalleMatricula objNDM = new clsNDetalleMatricula();
        
        if (cmbMatricula.getSelectedItem() != null && cmbCurso.getSelectedItem() != null) {
            
            // 1. Obtener los items seleccionados
            
            clsItem matItem = (clsItem) cmbMatricula.getSelectedItem();
            clsItem cursoItem = (clsItem) cmbCurso.getSelectedItem();

            // 2. Pasar a la entidad (ID de matrícula convertido a int)
            objEDM.setIdmatricula(Integer.parseInt(matItem.getId()));
            objEDM.setCodcurso(cursoItem.getId());

            // 3. Ejecutar acción
            if (objNDM.mtdAgregarDetalle(objEDM)) {
                JOptionPane.showMessageDialog(null, "Curso agregado a la matrícula " + matItem.getId());
                mtdListar(objEDM.getIdmatricula());
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar curso");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una matrícula y un curso");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        clsEDetalleMatricula objEDM = new clsEDetalleMatricula();
        clsNDetalleMatricula objNDM = new clsNDetalleMatricula();
        
        int fila = tblDetalleMatricula.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un curso de la tabla para modificar");
            return;
        }

        // ID de la matrícula actual del combo
        clsItem matItem = (clsItem) cmbMatricula.getSelectedItem();
        // Nuevo curso seleccionado en el combo
        clsItem cursoNuevo = (clsItem) cmbCurso.getSelectedItem();
        // Curso antiguo (el que está en la tabla)
        String cursoAntiguo = tblDetalleMatricula.getValueAt(fila, 0).toString();

        // Primero eliminamos el antiguo y luego agregamos el nuevo
        objEDM.setIdmatricula(Integer.parseInt(matItem.getId()));
        objEDM.setCodcurso(cursoAntiguo);

        if (objNDM.mtdEliminarDetalle(objEDM)) {
            objEDM.setCodcurso(cursoNuevo.getId());
            if (objNDM.mtdAgregarDetalle(objEDM)) {
                JOptionPane.showMessageDialog(null, "Curso actualizado correctamente");
                mtdListar(objEDM.getIdmatricula());
            }
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        clsEDetalleMatricula objEDM = new clsEDetalleMatricula();
        clsNDetalleMatricula objNDM = new clsNDetalleMatricula();
        
        int fila = tblDetalleMatricula.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione el curso que desea retirar de la lista");
            return;
        }

        clsItem matItem = (clsItem) cmbMatricula.getSelectedItem();
        String codCurso = tblDetalleMatricula.getValueAt(fila, 0).toString();

        objEDM.setIdmatricula(Integer.parseInt(matItem.getId()));
        objEDM.setCodcurso(codCurso);

        int resp = JOptionPane.showConfirmDialog(null, "¿Seguro que desea retirar este curso?");
        if (resp == JOptionPane.YES_OPTION) {
            if (objNDM.mtdEliminarDetalle(objEDM)) {
                mtdListar(objEDM.getIdmatricula());
                JOptionPane.showMessageDialog(null, "Curso retirado");
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        mtdLimpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String idABuscar = txtBCodigo.getText(); // O el campo de búsqueda que tengas

        if (idABuscar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID de matrícula");
            return;
        }

        // Buscamos en el combo si existe ese ID
        boolean encontrado = false;
        for (int i = 0; i < cmbMatricula.getItemCount(); i++) {
            clsItem item = (clsItem) cmbMatricula.getItemAt(i);
            if (item.getId().equals(idABuscar)) {
                cmbMatricula.setSelectedIndex(i);
                encontrado = true;
                break;
            }
        }

        if (encontrado) {
            // Al seleccionar el combo, el evento ActionPerformed debería disparar el mtdListar
            mtdListar(Integer.parseInt(idABuscar));
        } else {
            JOptionPane.showMessageDialog(null, "La matrícula no existe");
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblDetalleMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleMatriculaMouseClicked

        int filaSeleccionada = tblDetalleMatricula.getSelectedRow();
        if (filaSeleccionada != -1) {
            // Obtenemos el ID de matrícula y el Curso de la tabla
            String idMat = tblDetalleMatricula.getValueAt(filaSeleccionada, 0).toString();
            String cursoNom = tblDetalleMatricula.getValueAt(filaSeleccionada, 1).toString();

            // Sincronizar Combos
            mtdSeleccionarCombo(cmbMatricula, idMat);
            mtdSeleccionarCombo(cmbCurso, cursoNom);
        }

    }//GEN-LAST:event_tblDetalleMatriculaMouseClicked

    private void mtdSeleccionarCombo(javax.swing.JComboBox combo, String valor) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            if (combo.getItemAt(i).toString().equals(valor)) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        if (cmbMatricula.getSelectedItem() != null) {
            clsItem mat = (clsItem) cmbMatricula.getSelectedItem();
            mtdListar(Integer.parseInt(mat.getId()));
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una matrícula para listar sus cursos");
        }
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmDetalleMatricula().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmbCurso;
    private javax.swing.JComboBox cmbMatricula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBCodigo;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblIdMatricula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblDetalleMatricula;
    private javax.swing.JTextField txtBCodigo;
    // End of variables declaration//GEN-END:variables
}
