/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaEntidad.clsEDetalleClase;
import CapaNegocio.clsItem;
import CapaNegocio.clsNAlumno;
import CapaNegocio.clsNClase;
import CapaNegocio.clsNDetalleClase;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author david
 */
public class frmDetalleClase extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmDetalleClase.class.getName());

    /**
     * Creates new form frmCargo
     */
    
    //DEFINIR UNA NUEVA TABLA
    public static DefaultTableModel modelo = new DefaultTableModel();
    public static int fila = 0;
    
    public frmDetalleClase() {
        initComponents();
        
        //DEFINIR LAS COLUMNAS DE LA TABLA
        modelo.addColumn("ID CLASE");
        modelo.addColumn("COD ALUMNO");
        modelo.addColumn("NOMBRE ALUMNO");
        
        tblDetalleClase.setModel(modelo);
        
        mtdCargarCombos();
        
    }
    
    private void mtdLimpiar() {
        cmbClase.setSelectedIndex(0);
        cmbAlumno.setSelectedIndex(0);
        txtBCodigo.setText("");
        // Limpiar tabla
        modelo.setRowCount(0);
    }
    
    private void mtdCargarCombos() {
        
        clsNClase objNCl = new clsNClase();
        clsNAlumno objNAl = new clsNAlumno();
        
        try {
            // Cargar Clases
            ResultSet rsC = objNCl.mtdListarClase();
            cmbClase.removeAllItems();
            while (rsC.next()) {
                cmbClase.addItem(new clsItem(rsC.getString("idclase"), rsC.getString("idclase")));
            }

            // Cargar Alumnos
            ResultSet rsA = objNAl.mtdListarAlumno();
            cmbAlumno.removeAllItems();
            while (rsA.next()) {
                cmbAlumno.addItem(new clsItem(rsA.getString("codigo"), rsA.getString("nombre")));
            }
        } catch (Exception e) {
            System.out.println("Error combos: " + e.getMessage());
        }
    }

    public void mtdListar(String idClase) {
        
        clsEDetalleClase objEDC = new clsEDetalleClase();
        clsNDetalleClase objNDC = new clsNDetalleClase();
        
        modelo = new DefaultTableModel();
        modelo.addColumn("ID CLASE");
        modelo.addColumn("COD ALUMNO");
        modelo.addColumn("NOMBRE ALUMNO");
        tblDetalleClase.setModel(modelo);

        objEDC.setIdclase(idClase);
        ResultSet rs = objNDC.mtdListarDetalleClase(objEDC);
        Object[] fila = new Object[3];

        try {
            while (rs.next()) {
                fila[0] = idClase;
                fila[1] = rs.getString("codalumno");
                fila[2] = rs.getString("nombre");
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIdMatricula = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        cmbClase = new javax.swing.JComboBox();
        cmbAlumno = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleClase = new javax.swing.JTable();
        lblBCodigo = new javax.swing.JLabel();
        txtBCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("MATENIMIENTO DETALLE MATRICULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        lblIdMatricula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdMatricula.setForeground(new java.awt.Color(0, 0, 0));
        lblIdMatricula.setText("IDCLASE");

        lblCurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(0, 0, 0));
        lblCurso.setText("CODALUMNO");

        btnAgregar.setBackground(new java.awt.Color(204, 255, 255));
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(204, 255, 255));
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(204, 255, 255));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnListar.setBackground(new java.awt.Color(204, 255, 255));
        btnListar.setForeground(new java.awt.Color(0, 0, 0));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(this::btnListarActionPerformed);

        cmbClase.setBackground(new java.awt.Color(214, 234, 223));
        cmbClase.setForeground(new java.awt.Color(0, 0, 0));
        cmbClase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbAlumno.setBackground(new java.awt.Color(214, 234, 223));
        cmbAlumno.setForeground(new java.awt.Color(0, 0, 0));
        cmbAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdMatricula, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCurso, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbClase, 0, 285, Short.MAX_VALUE)
                            .addComponent(cmbAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdMatricula)
                    .addComponent(cmbClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(cmbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnListar))
                .addGap(33, 33, 33))
        );

        tblDetalleClase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetalleClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleClaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetalleClase);

        lblBCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBCodigo.setText("BUSCAR CODIGO");

        txtBCodigo.setBackground(new java.awt.Color(214, 234, 223));
        txtBCodigo.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscar.setBackground(new java.awt.Color(204, 255, 255));
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblBCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBCodigo)
                    .addComponent(txtBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        clsEDetalleClase objEDC = new clsEDetalleClase();
        clsNDetalleClase objNDC = new clsNDetalleClase();
        
        clsItem clase = (clsItem) cmbClase.getSelectedItem();
        clsItem alumno = (clsItem) cmbAlumno.getSelectedItem();

        objEDC.setIdclase(clase.getId());
        objEDC.setCodalumno(alumno.getId());

        if (objNDC.mtdAgregarDetalleClase(objEDC)) {
            JOptionPane.showMessageDialog(null, "Alumno asignado a la clase");
            mtdListar(clase.getId());
        } else {
            JOptionPane.showMessageDialog(null, "Error: El alumno ya está en esta clase");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        clsEDetalleClase objEDC = new clsEDetalleClase();
        clsNDetalleClase objNDC = new clsNDetalleClase();
        
        int filaS = tblDetalleClase.getSelectedRow();
        if (filaS != -1) {
            objEDC.setIdclase(tblDetalleClase.getValueAt(filaS, 0).toString());
            objEDC.setCodalumno(tblDetalleClase.getValueAt(filaS, 1).toString());

            if (objNDC.mtdEliminarDetalleClase(objEDC)) {
                JOptionPane.showMessageDialog(null, "Alumno retirado de la clase");
                mtdListar(objEDC.getIdclase());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un alumno de la tabla");
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        mtdLimpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String buscar = txtBCodigo.getText();
        boolean encontrado = false;
        for (int i = 0; i < cmbClase.getItemCount(); i++) {
            if (cmbClase.getItemAt(i).toString().equals(buscar)) {
                cmbClase.setSelectedIndex(i);
                encontrado = true;
                break;
            }
        }
        if (!encontrado)
            JOptionPane.showMessageDialog(null, "Clase no encontrada");
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblDetalleClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleClaseMouseClicked

        int filaSeleccionada = tblDetalleClase.getSelectedRow();
        if (filaSeleccionada != -1) {
            // Obtenemos el ID de matrícula y el Curso de la tabla
            String idMat = tblDetalleClase.getValueAt(filaSeleccionada, 0).toString();
            String cursoNom = tblDetalleClase.getValueAt(filaSeleccionada, 1).toString();

            // Sincronizar Combos
            mtdSeleccionarCombo(cmbClase, idMat);
            mtdSeleccionarCombo(cmbAlumno, cursoNom);
        }

    }//GEN-LAST:event_tblDetalleClaseMouseClicked

    private void mtdSeleccionarCombo(javax.swing.JComboBox combo, String valor) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            if (combo.getItemAt(i).toString().equals(valor)) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        if (cmbClase.getSelectedItem() != null) {
            clsItem clase = (clsItem) cmbClase.getSelectedItem();
            // ELIMINADO: Integer.parseInt (porque idclase es String)
            mtdListar(clase.getId());
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una clase para listar");
        }
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmDetalleClase().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmbAlumno;
    private javax.swing.JComboBox cmbClase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBCodigo;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblIdMatricula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblDetalleClase;
    private javax.swing.JTextField txtBCodigo;
    // End of variables declaration//GEN-END:variables
}
