/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaEntidad.clsEMatricula;
import CapaNegocio.clsItem;
import CapaNegocio.clsNAlumno;
import CapaNegocio.clsNEmpleado;
import CapaNegocio.clsNMatricula;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author david
 */
public class frmMatricula extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMatricula.class.getName());

    /**
     * Creates new form frmCargo
     */
    
    //DEFINIR UNA NUEVA TABLA
    public static DefaultTableModel modelo = new DefaultTableModel();
    public static int fila = 0;
    
    public frmMatricula() {
        initComponents();
        
        //DEFINIR LAS COLUMNAS DE LA TABLA
        modelo.addColumn("CODIGO");
        modelo.addColumn("DESCRIPCION");
        
        tblMatricula.setModel(modelo);
        
        mtdCargarCombos();
    }
    
    private void mtdCargarCombos() {
        
        clsNEmpleado objNE = new clsNEmpleado();
        clsNAlumno objNA = new clsNAlumno();
        
        try {
            // Cargar Empleados
            ResultSet rsE = objNE.mtdListarEmpleado();
            cmbEmpleado.removeAllItems();
            while (rsE.next()) {
                cmbEmpleado.addItem(new clsItem(rsE.getString("dni"), rsE.getString("nombre")));
            }

            // Cargar Alumnos
            ResultSet rsA = objNA.mtdListarAlumno();
            cmbAlumno.removeAllItems();
            while (rsA.next()) {
                cmbAlumno.addItem(new clsItem(rsA.getString("codigo"), rsA.getString("nombre")));
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    public void mtdListar() {
        
        clsNMatricula objNM = new clsNMatricula();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Fecha");
        modelo.addColumn("Estado");
        modelo.addColumn("Empleado");
        modelo.addColumn("Alumno");

        tblMatricula.setModel(modelo);
        ResultSet rs = objNM.mtdListarMatricula();
        Object[] fila = new Object[5];

        try {
            while (rs.next()) {
                fila[0] = rs.getInt("idmatricula");
                fila[1] = rs.getInt("fecha");
                fila[2] = rs.getInt("estado");
                fila[3] = rs.getString("nombre_empleado");
                fila[4] = rs.getString("nombre_alumno");
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void mtdLimpiar() {
        txtIdMatricula.setText("");
        txtFecha.setText("");
        txtEstado.setText("");
        cmbEmpleado.setSelectedIndex(0);
        cmbAlumno.setSelectedIndex(0);
        txtIdMatricula.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIdmatricula = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtIdMatricula = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        cmbEmpleado = new javax.swing.JComboBox();
        cmbAlumno = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatricula = new javax.swing.JTable();
        lblBCodigo = new javax.swing.JLabel();
        txtBCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("MATENIMIENTO MATRICULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        lblIdmatricula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdmatricula.setText("IDMATRICULA");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescripcion.setText("FECHA");

        txtIdMatricula.setBackground(new java.awt.Color(214, 234, 223));

        txtFecha.setBackground(new java.awt.Color(214, 234, 223));

        btnAgregar.setBackground(new java.awt.Color(204, 255, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(204, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(204, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnListar.setBackground(new java.awt.Color(204, 255, 255));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(this::btnListarActionPerformed);

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setText("ESTADO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("EMPLEADO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ALUMNO");

        txtEstado.setBackground(new java.awt.Color(214, 234, 223));

        cmbEmpleado.setBackground(new java.awt.Color(214, 234, 223));
        cmbEmpleado.setEditable(true);
        cmbEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbAlumno.setBackground(new java.awt.Color(214, 234, 223));
        cmbAlumno.setEditable(true);
        cmbAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescripcion)
                                .addComponent(lblEstado))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblIdmatricula)
                                .addGap(10, 10, 10)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(txtIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstado)
                            .addComponent(cmbEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdmatricula)
                    .addComponent(txtIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnListar))
                .addGap(21, 21, 21))
        );

        tblMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMatriculaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMatricula);

        lblBCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBCodigo.setText("BUSCAR CODIGO");

        txtBCodigo.setBackground(new java.awt.Color(214, 234, 223));

        btnBuscar.setBackground(new java.awt.Color(204, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblBCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(0, 218, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBCodigo)
                    .addComponent(txtBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        clsEMatricula objEM = new clsEMatricula();
        clsNMatricula objNM = new clsNMatricula();
        
        objEM.setIdmatricula(Integer.parseInt(txtIdMatricula.getText()));
        objEM.setFecha(Integer.parseInt(txtFecha.getText()));
        objEM.setEstado(Integer.parseInt(txtEstado.getText()));

        clsItem emp = (clsItem) cmbEmpleado.getSelectedItem();
        clsItem alu = (clsItem) cmbAlumno.getSelectedItem();

        objEM.setDniemp(emp.getId());
        objEM.setCodalumno(alu.getId());

        if (objNM.mtdAgregarMatricula(objEM)) {
            JOptionPane.showMessageDialog(null, "Matrícula realizada");
            mtdListar();
            mtdLimpiar();
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        clsEMatricula objEM = new clsEMatricula();
        clsNMatricula objNM = new clsNMatricula();
        
        objEM.setIdmatricula(Integer.parseInt(txtIdMatricula.getText()));
        objEM.setFecha(Integer.parseInt(txtFecha.getText()));
        objEM.setEstado(Integer.parseInt(txtEstado.getText()));

        clsItem emp = (clsItem) cmbEmpleado.getSelectedItem();
        clsItem alu = (clsItem) cmbAlumno.getSelectedItem();

        objEM.setDniemp(emp.getId());
        objEM.setCodalumno(alu.getId());

        if (objNM.mtdModificarMatricula(objEM)) {
            JOptionPane.showMessageDialog(null, "Matrícula actualizada");
            mtdListar();
            mtdLimpiar();
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        clsEMatricula objEM = new clsEMatricula();
        clsNMatricula objNM = new clsNMatricula();
        
        objEM.setIdmatricula(Integer.parseInt(txtIdMatricula.getText()));
        if (objNM.mtdEliminarMatricula(objEM)) {
            mtdListar();
            mtdLimpiar();
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        mtdLimpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        clsEMatricula objEM = new clsEMatricula();
        clsNMatricula objNM = new clsNMatricula();
        
        try {
            // 1. Validar que el campo de búsqueda no esté vacío
            if (txtBCodigo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese un ID de Matrícula para buscar");
                return;
            }

            // 2. Pasar el ID (int) a la entidad
            objEM.setIdmatricula(Integer.parseInt(txtBCodigo.getText()));

            // 3. Llamar al método de la Capa de Negocio
            ResultSet rs = objNM.mtdBuscarMatricula(objEM);

            if (rs.next()) {
                // 4. Llenar los campos de texto
                txtIdMatricula.setText(String.valueOf(rs.getInt("idmatricula")));
                txtFecha.setText(String.valueOf(rs.getInt("fecha")));
                txtEstado.setText(String.valueOf(rs.getInt("estado")));

                // 5. Recuperar los IDs (FK) de la base de datos
                String dniVal = rs.getString("dniemp");
                String aluVal = rs.getString("codalumno");

                // 6. Posicionar los ComboBoxes usando el ID oculto
                mtdSeleccionarComboPorId(cmbEmpleado, dniVal);
                mtdSeleccionarComboPorId(cmbAlumno, aluVal);

            } else {
                JOptionPane.showMessageDialog(null, "No se encontró la matrícula con el ID especificado");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de búsqueda debe ser un número entero");
        } catch (SQLException e) {
            System.out.println("Error en búsqueda: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void mtdSeleccionarComboPorId(JComboBox combo, String id) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            // Convertimos el ítem actual a nuestro objeto clsItem
            clsItem item = (clsItem) combo.getItemAt(i);

            // Comparamos el ID del objeto con el ID que traemos de la BD
            if (item.getId().equals(id)) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void tblMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatriculaMouseClicked
        int fila = tblMatricula.getSelectedRow();
        if (fila != -1) {
            txtIdMatricula.setText(tblMatricula.getValueAt(fila, 0).toString());
            txtFecha.setText(tblMatricula.getValueAt(fila, 1).toString());
            txtEstado.setText(tblMatricula.getValueAt(fila, 2).toString());

            // Seleccionar en combos por nombre (Texto visible en la tabla)
            mtdSeleccionarCombo(cmbEmpleado, tblMatricula.getValueAt(fila, 3).toString());
            mtdSeleccionarCombo(cmbAlumno, tblMatricula.getValueAt(fila, 4).toString());
        }
    }//GEN-LAST:event_tblMatriculaMouseClicked

    private void mtdSeleccionarCombo(JComboBox combo, String valor) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            if (combo.getItemAt(i).toString().equals(valor)) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        mtdListar();
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMatricula().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmbAlumno;
    private javax.swing.JComboBox cmbEmpleado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdmatricula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblMatricula;
    private javax.swing.JTextField txtBCodigo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdMatricula;
    // End of variables declaration//GEN-END:variables
}
